# Generated by Django 4.1.2 on 2022-10-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=50, null=True)),
                ('lottery_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_prize', models.CharField(blank=True, max_length=100, null=True)),
                ('consolation_prize', models.CharField(blank=True, max_length=250, null=True)),
                ('second_prize', models.TextField(blank=True, null=True)),
                ('third_prize', models.TextField(blank=True, null=True)),
                ('fourth_prize', models.TextField(blank=True, null=True)),
                ('fifth_prize', models.TextField(blank=True, null=True)),
                ('sixth_prize', models.TextField(blank=True, null=True)),
                ('seventh_prize', models.TextField(blank=True, null=True)),
                ('eighth_prize', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'lottery_new',
                'managed': False,
            },
        ),
    ]
